
version: '3.8'

services:
  smartlib_catalog:
    build: .
    ports:

      - "80:80"



    environment:
     # - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/SmartLib
      - SPRING_DATASOURCE_URL=jdbc:postgresql://smartlib-1.crqkcw4gkx25.eu-north-1.rds.amazonaws.com:5432/smartlib
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=smartlib

    depends_on:
      - db
    networks:
      - smartlib-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=smartlib
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=smartlib
    ports:
      - "5433:5432"

    networks:
      - smartlib-network

networks:
  smartlib-network:

    driver: bridge

