name: 'Publish API Image'
description: 'Publish API Image for Java Application'
inputs:
  java-environment:
    description: 'Java environment (e.g., dev, prod)'
    default: 'dev'
  published-app:
    description: 'Path to the built Java application (e.g., target/*.jar)'
    default: './target/fplarache-smartlib-catalog-0.0.1-SNAPSHOT.jar'
  dockerfile:
    description: 'Path to the Dockerfile'
    default: '../../Dockerfile'
  cmd:
    description: 'Command to run the Java app (e.g., java -jar app.jar)'
    default: 'java -jar /app.jar'
  image-short-name:
    description: 'Short name for the Docker image'
    default: 'fplarache-smartlib-catalog'
  image-prefix:
    description: 'Prefix for the Docker image name (ensure no leading dash)'
    default: 'dev'
  image-tag:
    description: 'Tag for the Docker image (e.g., v1.0.0)'
    default: 'latest'
  ecr-registry:
    description: 'Amazon ECR registry URL (e.g., 123456789012.dkr.ecr.us-west-1.amazonaws.com)'
    default: '774305596814.dkr.ecr.eu-north-1.amazonaws.com'

outputs:
  image-uri:
    description: 'The URI of the pushed image'
    value: ${{ inputs.ecr-registry }}/${{ inputs.image-prefix }}-${{ inputs.image-short-name }}:latest

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Extract input parameters
        IMAGE_PREFIX="${{ inputs.image-prefix }}"
        IMAGE_SHORT_NAME="${{ inputs.image-short-name }}"
        IMAGE_TAG="${{ inputs.image-tag }}"
        ECR_REGISTRY="${{ inputs.ecr-registry }}"
        JAVA_APP_PATH="${{ inputs.published-app }}"
        DOCKERFILE_PATH="${{ inputs.dockerfile }}"
        JAVA_ENVIRONMENT="${{ inputs.java-environment }}"

        # Step 1: Validate inputs
        if [[ -z "$IMAGE_PREFIX" ]]; then
          echo "Error: IMAGE_PREFIX is not set or empty"
          exit 1
        fi
        if [[ -z "$IMAGE_SHORT_NAME" ]]; then
          echo "Error: IMAGE_SHORT_NAME is not set or empty"
          exit 1
        fi
        if [[ -z "$IMAGE_TAG" ]]; then
          echo "Error: IMAGE_TAG is not set or empty"
          exit 1
        fi
        if [[ -z "$ECR_REGISTRY" ]]; then
          echo "Error: ECR_REGISTRY is not set or empty"
          exit 1
        fi
        if [[ -z "$JAVA_APP_PATH" || ! -f "$JAVA_APP_PATH" ]]; then
          echo "Error: JAVA_APP_PATH is not set or does not point to a valid file"
          exit 1
        fi
        if [[ -z "$DOCKERFILE_PATH" || ! -f "$DOCKERFILE_PATH" ]]; then
          echo "Error: DOCKERFILE_PATH is not set or does not point to a valid file"
          exit 1
        fi

        # Step 2: Ensure the image name is correctly formatted
        # Remove leading hyphen from the image prefix, if exists
        IMAGE_PREFIX=$(echo $IMAGE_PREFIX | sed 's/^-//')

        # Step 3: Construct the full image name
        IMAGENAME="${ECR_REGISTRY}/${IMAGE_PREFIX}-${IMAGE_SHORT_NAME}:${IMAGE_TAG}"

        # Step 4: Display the formatted image name
        echo "Formatted image name: $IMAGENAME"

        # Step 5: Build the Docker image
        docker build \
          --build-arg JAVA_API_PATH_ARG=$JAVA_APP_PATH \
          --build-arg JAVA_ENVIRONMENT_ARG=$JAVA_ENVIRONMENT \
          -f $DOCKERFILE_PATH \
          -t $IMAGENAME .

        # Step 6: Push the Docker image
        docker push $IMAGENAME

        # Step 7: Output the image URI
        echo "image-uri=$IMAGENAME" >> $GITHUB_OUTPUT
